@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "controller.Controller#startGame(int,int)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "controller.Controller",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_104069929 { 
   	label=model
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_2058798240 { 
   	label=Room
	labeljust=l
	fillcolor=white
	style=filled
   
   Room104069929XXXaddNeighbour2553083[
	label="+ addNeighbour()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10;  A szoba szomszédai közé felvesz egy szobát.&#10;  @param room a szomszédok listájába felvenni kívánt szoba&#10; "
	fontcolor=darkgreen
];

Room104069929XXXaddPerson1907849355[
	label="+ addPerson()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10;  A szobában elhelyez egy személyt amennyiben a szoba nincs tele.&#10;  @param person az elhelyezni kívánt személy&#10; "
	fontcolor=darkgreen
];

Room104069929XXXinitItem2289459[
	label="+ initItem()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10;  A szobában elhelyez egy tárgyat.&#10;  @param item az elhelyezni kívánt tárgy&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_637428636 { 
   	label=controller
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1872830130 { 
   	label=Controller
	labeljust=l
	fillcolor=white
	style=filled
   
   Controller637428636XXXstartGame515322732[
	label="+ startGame()"
	style=filled
	fillcolor=white
	tooltip="Controller

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

'edges    
Controller637428636XXXstartGame515322732 -> Room104069929XXXaddNeighbour2553083;
Controller637428636XXXstartGame515322732 -> Room104069929XXXaddPerson1907849355;
Controller637428636XXXstartGame515322732 -> Room104069929XXXinitItem2289459;
    
}
@enduml