@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "controller.Controller#enterButtonPressed()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "controller.Controller",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_104069929 { 
   	label=model
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1002356433 { 
   	label=Cleaner
	labeljust=l
	fillcolor=white
	style=filled
   
   Cleaner104069929XXXenterRoom2553083[
	label="+ enterRoom()"
	style=filled
	fillcolor=white
	tooltip="Cleaner

&#10;  A takarító mozgását végrehajtó metódus.&#10;  A takarító mozgási metódusa ugyanazzal kezdődik, mint az eredeti, ősben definiált.&#10;  Majd amennyiben a location-je módosult, meghívja a location-ön a setGas(false) és a clean() metódusait.&#10;  @param roomTo az a szoba, ahova át akar lépni&#10; "
	fontcolor=darkgreen
];

Cleaner104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Cleaner

&#10;  A takarító egy személlyel való találkozást kezeli le.&#10;  A takarító nem csinál semmit&#10;  @param person a személy, akivel találkozik&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1293994499 { 
   	label=Teacher
	labeljust=l
	fillcolor=white
	style=filled
   
   Teacher104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Teacher

&#10;  A tanár egy személlyel való találkozást kezeli le.&#10;  A személyt, akivel találkozik, megpróbálja megölni, amennyiben nincs lebénulva.&#10;  @param person a személy, akivel találkozik&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1378105930 { 
   	label=AirFresher
	labeljust=l
	fillcolor=white
	style=filled
   
   AirFresher104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="AirFresher

&#10;  Egy személlyel való találkozást kezeli, ha a földön van.&#10;  Nincsen semmilyen hatása a földön.&#10;  @param person Az a személy, akivel találkozik&#10; "
	fontcolor=darkgreen
];

AirFresher104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="AirFresher

&#10;  Idő telése a tárgyon&#10;  Mivel egyszerhasználatos tárgy, így nem történik vele&#10;  semmi az idő múlásával.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1541209638 { 
   	label=Person
	labeljust=l
	fillcolor=white
	style=filled
   
   Person104069929XXXaddItem2289459[
	label="+ addItem()"
	style=filled
	fillcolor=white
	tooltip="Person

&#10;  Egy tárgy felvétele, amennyiben a lehetséges&#10;  @param item a felvenni kívánt tárgy&#10; "
	fontcolor=darkgreen
];

Person104069929XXXenterRoom2553083[
	label="+ enterRoom()"
	style=filled
	fillcolor=white
	tooltip="Person

&#10;  A személy mozgását végrehajtó metódus.&#10;  Ha a személy nincs elkábulva, továbbítja a jelenlegi szobájának az átlépés igényét.&#10;  A két szoba felelőssége, hogy a személyt beengedi-e.&#10;  Amennyiben sikeresen átlép a másik szobába, frissíti a tárgyainak tartózkodási helyét is.&#10;  @param roomTo az a szoba, ahova át akar lépni&#10; "
	fontcolor=darkgreen
];

Person104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Person

&#10;  Egy személlyel való találkozást kezeli le.&#10;  @param person a személy, akivel találkozik&#10; "
	fontcolor=darkgreen
];

Person104069929XXXremoveItem2289459[
	label="+ removeItem()"
	style=filled
	fillcolor=white
	tooltip="Person

&#10;  Egy tárgy törlése a személy kezéből.&#10;  @param item a törölni kívánt tárgy&#10; "
	fontcolor=darkgreen
];

Person104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="Person

&#10;  Időtelés szimulálása.&#10;  A személy továbbítja az eltelt időt (time) a nála lévő tárgyaknak.&#10;  Amennyiben kábult a személy, csökkenti a hátralévő kábulási időt.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_159551353 { 
   	label=BeerGlass
	labeljust=l
	fillcolor=white
	style=filled
   
   BeerGlass104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="BeerGlass

&#10;  Egy személlyel való találkozást kezeli, ha a földön van.&#10;  Nincsen semmilyen hatása, mert ha a földön van nem tud senkit megvédeni.&#10;  @param person Az a személy, akivel találkozik&#10; "
	fontcolor=darkgreen
];

BeerGlass104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="BeerGlass

&#10;  Idő telése a tárgyon&#10;  Ha aktiválva van a tárgy, akkor a kapott paraméterrel csökkenti az objektum timeRemaining tagváltozóját.&#10;  Ha a timeRemaining elérte a 0-t, akkor kezdeményezi aktuális birtokosánál a tárgy megsemmisítését.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1669420968 { 
   	label=SlideRule
	labeljust=l
	fillcolor=white
	style=filled
   
   SlideRule104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="SlideRule

&#10;  Találkozás személlyel&#10;  Nem csinál semmit, mert ha földön van nincs funkciója.&#10;  @param person a személy, akivel találkozik a tárgy&#10; "
	fontcolor=darkgreen
];

SlideRule104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="SlideRule

&#10;  Idő telése a tárgyon&#10;  Mivel egyszerhasználatos tárgy, így nem történik vele semmi az idő múlásával.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1705623114 { 
   	label=Transistor
	labeljust=l
	fillcolor=white
	style=filled
   
   Transistor104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Transistor

&#10;  Találkozás emberrel&#10;  Nem csinál semmit.&#10;  @param person a személy, akivel találkozik a tárgy&#10; "
	fontcolor=darkgreen
];

Transistor104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="Transistor

&#10;  Idő telése a tárgyon&#10;  Nem történik vele semmi.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1733563306 { 
   	label=Student
	labeljust=l
	fillcolor=white
	style=filled
   
   Student104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Student

&#10;  Egy személlyel való találkozást kezeli le. Köszön a személynek.&#10;  @param person a személy, akivel találkozik&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2011797581 { 
   	label=Rag
	labeljust=l
	fillcolor=white
	style=filled
   
   Rag104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Rag

&#10;  Egy személlyel való találkozást lekezelése.&#10;  Az aktivált rongy kezdeményezi a személy megbénítását.&#10;  @param person a személy, akivel találkozik a tárgy&#10; "
	fontcolor=darkgreen
];

Rag104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="Rag

&#10;  Idő telése a tárgyra&#10;  Ha aktiválva van a tárgy, akkor a timeRemaining értékét&#10;  csökkenti time-mal. Ha elérte a 0-t, akkor aktuális birtokosánál kezdeményezi a tárgy&#10;  megsemmisítését.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2058534616 { 
   	label=Item
	labeljust=l
	fillcolor=white
	style=filled
   
   Item104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Item

&#10;  Ha a tárgy a földön van egy szobában,&#10;  a szobába belépő új személyekkel való találkozást kezeli.&#10;  @param person a személy, akivel találkozik a tárgy&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2058635953 { 
   	label=Mask
	labeljust=l
	fillcolor=white
	style=filled
   
   Mask104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Mask

&#10;  Találkozás személlyel&#10;  Nem csinál semmit, mert ha földön van nincs kit megvédenie.&#10;  @param person a személy, akivel találkozik a tárgy&#10; "
	fontcolor=darkgreen
];

Mask104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="Mask

&#10;  Idő telése a maszkon&#10;  Ha aktiválva van a tárgy, akkor a timeRemaining értékét&#10;  csökkenti time-mal. Ha elérte a 0-t, akkor adott értékkel csökkenti a durationt és&#10;  visszaállítja az activatedet hamisra. Ha a duration elérte a 0-t akkor aktuális&#10;  birtokosánál kezdeményezi a tárgy megsemmisítését&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2058798240 { 
   	label=Room
	labeljust=l
	fillcolor=white
	style=filled
   
   Room104069929XXXacceptPerson1907849355[
	label="+ acceptPerson()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10;  A paraméterként kapott személyt engedi be a szobába.&#10;  Amennyiben a szoba kapacitása kimerült nem engedi be a személyt. A visszatérési&#10;  értéke a beengedés sikeressége. Ha beengedi a személyt, felel az új személy és a&#10;  szobában tartózkodó személyek kölcsönös találkozásáért, illetve az új személy és&#10;  szobában levő tárgyak találkozásáért. Ha a szoba mérgezett, felel a belépő játékos&#10;  elkábításáért.&#10;  Felel a ragacsosság növeléséért.&#10;  @param person a belépő személy&#10;  @return {@code true} ha sikeresen belépett a szobába {@code false} egyébként&#10; "
	fontcolor=darkgreen
];

Room104069929XXXclean0[
	label="+ clean()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10;  A szoba takarítása.&#10;  Stickiness nullázása. A legutóbb érkezett ember (ez a takarító,&#10;  aki a szobába jövetelkor hívta a függvényt) kivételével&#10;  összes szobában tartózkodó embert átteszi egy másik szobába, amennyiben teheti.&#10;  A szomszédok listájában elölről indul, és ameddig tudja tenni az embereket, addig oda teszi&#10;  (meghívja az adott emberre az enterRoom(r3) metódust az adott r3 szomszédot átadva),&#10;  ha pedig nem tudja, akkor a következő szomszéddal próbálkozik.&#10;  Ha az összes szomszédon végig ment és még mindig maradt ember a szobában, akkor ők ott maradhatnak.&#10; "
	fontcolor=darkgreen
];

Room104069929XXXmovePerson1681949660[
	label="+ movePerson()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10; Ha a szoba jelenleg nincs aktívan elátkozva, a&#10;  paraméterként kapott személy a paraméterként kapott szobába léptetésének igényét továbbítja. A kapott szoba&#10;  értesíti ennek sikerességéről és ő is ezzel tér vissza. Ha igazzal tér vissza, akkor&#10;  eltávolítja a személyt önmagából. Ha a szoba aktívan elátkozott, rögtön hamissal tér vissza.&#10;  @param person a személy, aki át akar lépni&#10;  @param roomTo a szoba, ahova át szeretne lépni&#10;  @return {@code true} ha sikeresen átlépett, {@code false} egyébként&#10; "
	fontcolor=darkgreen
];

Room104069929XXXpickUpItem2289459[
	label="+ pickUpItem()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10;  Egy tárgy felvételének kezdeményezése a szobánál.&#10;  Amennyiben a ragacsosság még nem érte el a határértékét,&#10;  a removeItem()-hez hasonlóan eltávolítja a tárgyat, majd igazzal visszatér.&#10;  Egyébként hamis visszatérési értékkel jelzi a személynek a sikertelen felvételt.&#10;  @param item a tárgy amit fel akarnak venni&#10;  @return {@code true} ha a tárgy felvehető {@code false} egyébként&#10; "
	fontcolor=darkgreen
];

Room104069929XXXremoveItem2289459[
	label="+ removeItem()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10;  Egy tárgy törlése a szobából.&#10;  @param item a törölni kívánt tárgy&#10; "
	fontcolor=darkgreen
];

Room104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="Room

&#10;  Idő telésének szimulálása. Funckiói:&#10;  Elátkozottsági állapot módosul.&#10;  Továbbítja az eltelt időt a benne lévő személyeknek és tárgyaknak.&#10;  A továbbra is szobában tartózkodó tárgyakat összetalálkoztatja minden személlyel és&#10;  minden személyt kölcsönösen összetalálkoztat egymással.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2058832910 { 
   	label=TVSZ
	labeljust=l
	fillcolor=white
	style=filled
   
   TVSZ104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="TVSZ

&#10;  Találkozás személlyel&#10;  Nem csinál semmit. a földön nem tud megvédeni senkit.&#10;  @param person a személy, akivel találkozik a tárgy&#10; "
	fontcolor=darkgreen
];

TVSZ104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="TVSZ

&#10;  Idő telése a TVSZ-en&#10;  Mivel egyszerhasználatos tárgy, így nem történik vele&#10;  semmi az idő múlásával.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2119370327 { 
   	label=Camembert
	labeljust=l
	fillcolor=white
	style=filled
   
   Camembert104069929XXXmeet1907849355[
	label="+ meet()"
	style=filled
	fillcolor=white
	tooltip="Camembert

&#10;  Egy személlyel való találkozást kezeli, ha a földön van.&#10;  Nincsen semmilyen hatása.&#10;  @param person Az a személy, akivel találkozik&#10; "
	fontcolor=darkgreen
];

Camembert104069929XXXtimeElapsed104431[
	label="+ timeElapsed()"
	style=filled
	fillcolor=white
	tooltip="Camembert

&#10;  Idő múlása tárgyon.&#10;  Az idő műlása nincs rá hastással, mert egyszerhasználatos tárgy.&#10;  @param time az eltelt idő&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3732 { 
   	label=ui
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1924555204 { 
   	label=GameWindow
	labeljust=l
	fillcolor=white
	style=filled
   
   GameWindow3732XXXreDraw0[
	label="+ reDraw()"
	style=filled
	fillcolor=white
	tooltip="GameWindow

null"
	fontcolor=darkgreen
];

GameWindow3732XXXshowPlayer214492645[
	label="+ showPlayer()"
	style=filled
	fillcolor=white
	tooltip="GameWindow

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_204909783 { 
   	label=PlayerPanel
	labeljust=l
	fillcolor=white
	style=filled
   
   PlayerPanel3732XXXreDraw0[
	label="+ reDraw()"
	style=filled
	fillcolor=white
	tooltip="PlayerPanel

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_637428636 { 
   	label=controller
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1872830130 { 
   	label=Controller
	labeljust=l
	fillcolor=white
	style=filled
   
   Controller637428636XXXenterButtonPressed0[
	label="+ enterButtonPressed()"
	style=filled
	fillcolor=white
	tooltip="Controller

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

'edges    
BeerGlass104069929XXXtimeElapsed104431 -> Person104069929XXXremoveItem2289459;
BeerGlass104069929XXXtimeElapsed104431 -> Room104069929XXXremoveItem2289459;
Cleaner104069929XXXenterRoom2553083 -> Person104069929XXXenterRoom2553083;
Cleaner104069929XXXenterRoom2553083 -> Room104069929XXXclean0;
Controller637428636XXXenterButtonPressed0 -> GameWindow3732XXXreDraw0;
Controller637428636XXXenterButtonPressed0 -> GameWindow3732XXXshowPlayer214492645;
Controller637428636XXXenterButtonPressed0 -> Person104069929XXXaddItem2289459;
Controller637428636XXXenterButtonPressed0 -> Person104069929XXXenterRoom2553083;
Controller637428636XXXenterButtonPressed0 -> Room104069929XXXtimeElapsed104431;
GameWindow3732XXXreDraw0 -> PlayerPanel3732XXXreDraw0;
GameWindow3732XXXshowPlayer214492645 -> GameWindow3732XXXreDraw0;
Item104069929XXXmeet1907849355 -> AirFresher104069929XXXmeet1907849355;
Item104069929XXXmeet1907849355 -> BeerGlass104069929XXXmeet1907849355;
Item104069929XXXmeet1907849355 -> Camembert104069929XXXmeet1907849355;
Item104069929XXXmeet1907849355 -> Mask104069929XXXmeet1907849355;
Item104069929XXXmeet1907849355 -> Rag104069929XXXmeet1907849355;
Item104069929XXXmeet1907849355 -> SlideRule104069929XXXmeet1907849355;
Item104069929XXXmeet1907849355 -> TVSZ104069929XXXmeet1907849355;
Item104069929XXXmeet1907849355 -> Transistor104069929XXXmeet1907849355;
Mask104069929XXXtimeElapsed104431 -> Person104069929XXXremoveItem2289459;
Mask104069929XXXtimeElapsed104431 -> Room104069929XXXremoveItem2289459;
Person104069929XXXaddItem2289459 -> Room104069929XXXpickUpItem2289459;
Person104069929XXXenterRoom2553083 -> Cleaner104069929XXXenterRoom2553083;
Person104069929XXXenterRoom2553083 -> Room104069929XXXmovePerson1681949660;
Person104069929XXXmeet1907849355 -> Cleaner104069929XXXmeet1907849355;
Person104069929XXXmeet1907849355 -> Student104069929XXXmeet1907849355;
Person104069929XXXmeet1907849355 -> Teacher104069929XXXmeet1907849355;
Rag104069929XXXtimeElapsed104431 -> Person104069929XXXremoveItem2289459;
Rag104069929XXXtimeElapsed104431 -> Room104069929XXXremoveItem2289459;
Room104069929XXXmovePerson1681949660 -> Room104069929XXXacceptPerson1907849355;
Room104069929XXXtimeElapsed104431 -> AirFresher104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> BeerGlass104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> Camembert104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> Item104069929XXXmeet1907849355;
Room104069929XXXtimeElapsed104431 -> Mask104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> Person104069929XXXmeet1907849355;
Room104069929XXXtimeElapsed104431 -> Person104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> Rag104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> Room104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> SlideRule104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> TVSZ104069929XXXtimeElapsed104431;
Room104069929XXXtimeElapsed104431 -> Transistor104069929XXXtimeElapsed104431;
    
}
@enduml